
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
  
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1/32
        - 100.0.0.0/8
        - 192.168.86.0/24
        - 172.30.32.0/24
      allow_bypass_login: true
    - type: homeassistant
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config
  
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: warning
  logs:
    custom_components.scheduler: debug
    homeassistant.components.nest: debug
    homeassistant.components.nest.climate_sdm: debug
    homeassistant.components.nest.camera_sdm: debug
    homeassistant.components.nest.sensor_sdm: debug
    homeassistant.helpers.config_entry_flow: debug
    homeassistant.helpers.config_entry_oauth2_flow: debug
    google_nest_sdm: debug
    google_nest_sdm.device: debug
    google_nest_sdm.device_manager: debug
    google_nest_sdm.google_nest_subscriber: debug
    google_nest_sdm.event: debug
    homeassistant.components.command_line: debug
    #homeassistant.components.http: debug
    
recorder:
  exclude:
    entity_globs:
      - sensor.*_high_freq
