{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 2,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "efa8b1d7-e94e-4886-a704-b61ce7c60a70"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 6,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 4,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "efa8b1d7-e94e-4886-a704-b61ce7c60a70"
          },
          "editorMode": "code",
          "expr": "homeassistant_sensor_battery_percent{entity=\"sensor.openmower_battery_percentage\"}",
          "instant": false,
          "interval": "1s",
          "legendFormat": "Battery",
          "range": true,
          "refId": "A"
        }
      ],
      "title": "Battery",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "efa8b1d7-e94e-4886-a704-b61ce7c60a70"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 11,
        "w": 24,
        "x": 0,
        "y": 6
      },
      "id": 1,
      "options": {
        "basemap": {
          "config": {
            "url": "http://openmower.2m.lt:5000/rgb/{z}/{x}/{y}.png?r=red&g=green&b=blue"
          },
          "name": "Layer 0",
          "type": "xyz"
        },
        "controls": {
          "mouseWheelZoom": true,
          "showAttribution": true,
          "showDebug": false,
          "showMeasure": false,
          "showScale": false,
          "showZoom": true
        },
        "layers": [
          {
            "config": {
              "arrow": 0,
              "style": {
                "color": {
                  "fixed": "dark-blue"
                },
                "lineWidth": 2,
                "opacity": 1,
                "rotation": {
                  "fixed": 0,
                  "max": 360,
                  "min": -360,
                  "mode": "mod"
                },
                "size": {
                  "fixed": 2,
                  "max": 15,
                  "min": 2
                },
                "symbol": {
                  "fixed": "img/icons/marker/circle.svg",
                  "mode": "fixed"
                },
                "textConfig": {
                  "fontSize": 12,
                  "offsetX": 0,
                  "offsetY": 0,
                  "textAlign": "center",
                  "textBaseline": "middle"
                }
              }
            },
            "name": "OpenMower",
            "tooltip": false,
            "type": "route"
          },
          {
            "config": {
              "icon": "https://openlayers.org/en/latest/examples/data/icon.png"
            },
            "name": "Layer 2",
            "opacity": 0.4,
            "tooltip": true,
            "type": "last-point-tracker"
          }
        ],
        "tooltip": {
          "mode": "details"
        },
        "view": {
          "allLayers": true,
          "id": "fit",
          "lat": 0,
          "lon": 0,
          "zoom": 22
        }
      },
      "pluginVersion": "10.0.3",
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "efa8b1d7-e94e-4886-a704-b61ce7c60a70"
          },
          "editorMode": "code",
          "expr": "homeassistant_sensor_unit_u0xb0{entity=~\".*openmower_position_(lat|lon)_high_freq\"}",
          "instant": false,
          "interval": "1s",
          "range": true,
          "refId": "A"
        }
      ],
      "title": "Travel Path",
      "transformations": [
        {
          "id": "renameByRegex",
          "options": {
            "regex": ".*_lat_.*",
            "renamePattern": "lat"
          }
        },
        {
          "id": "renameByRegex",
          "options": {
            "regex": ".*_lon_.*",
            "renamePattern": "lon"
          }
        },
        {
          "id": "joinByField",
          "options": {}
        }
      ],
      "type": "geomap"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "efa8b1d7-e94e-4886-a704-b61ce7c60a70"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            }
          },
          "decimals": 3,
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "dark-blue",
                "value": null
              },
              {
                "color": "#EAB839",
                "value": 0.02
              },
              {
                "color": "orange",
                "value": 0.03
              },
              {
                "color": "red",
                "value": 0.04
              },
              {
                "color": "#000000",
                "value": 2
              }
            ]
          },
          "unit": "lengthm"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 11,
        "w": 24,
        "x": 0,
        "y": 17
      },
      "id": 2,
      "options": {
        "basemap": {
          "config": {
            "url": "http://openmower.2m.lt:5000/rgb/{z}/{x}/{y}.png?r=red&g=green&b=blue"
          },
          "name": "Layer 0",
          "type": "xyz"
        },
        "controls": {
          "mouseWheelZoom": true,
          "showAttribution": true,
          "showDebug": false,
          "showMeasure": false,
          "showScale": false,
          "showZoom": true
        },
        "layers": [
          {
            "config": {
              "showLegend": true,
              "style": {
                "color": {
                  "field": "accuracy",
                  "fixed": "dark-green"
                },
                "opacity": 0.4,
                "rotation": {
                  "fixed": 0,
                  "max": 360,
                  "min": -360,
                  "mode": "mod"
                },
                "size": {
                  "fixed": 3,
                  "max": 15,
                  "min": 2
                },
                "symbol": {
                  "fixed": "img/icons/marker/circle.svg",
                  "mode": "fixed"
                },
                "textConfig": {
                  "fontSize": 12,
                  "offsetX": 0,
                  "offsetY": 0,
                  "textAlign": "center",
                  "textBaseline": "middle"
                }
              }
            },
            "location": {
              "mode": "auto"
            },
            "name": "Position Accuracy",
            "tooltip": false,
            "type": "markers"
          }
        ],
        "tooltip": {
          "mode": "details"
        },
        "view": {
          "allLayers": true,
          "id": "fit",
          "lat": 0,
          "lon": 0,
          "zoom": 22
        }
      },
      "pluginVersion": "10.0.3",
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "efa8b1d7-e94e-4886-a704-b61ce7c60a70"
          },
          "editorMode": "code",
          "expr": "homeassistant_sensor_unit_u0xb0{entity=~\".*openmower_position_(lat|lon)_high_freq\"}",
          "instant": false,
          "interval": "1s",
          "range": true,
          "refId": "A"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "efa8b1d7-e94e-4886-a704-b61ce7c60a70"
          },
          "editorMode": "code",
          "expr": "homeassistant_sensor_distance_m{entity=\"sensor.openmower_position_accuracy\"}",
          "hide": false,
          "instant": false,
          "interval": "1s",
          "range": true,
          "refId": "B"
        }
      ],
      "title": "Position Accuracy",
      "transformations": [
        {
          "id": "renameByRegex",
          "options": {
            "regex": ".*_lat_.*",
            "renamePattern": "lat"
          }
        },
        {
          "id": "renameByRegex",
          "options": {
            "regex": ".*_lon_.*",
            "renamePattern": "lon"
          }
        },
        {
          "id": "renameByRegex",
          "options": {
            "regex": ".*_position_.*",
            "renamePattern": "accuracy"
          }
        },
        {
          "id": "joinByField",
          "options": {}
        }
      ],
      "type": "geomap"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "efa8b1d7-e94e-4886-a704-b61ce7c60a70"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            }
          },
          "decimals": 3,
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "red",
                "value": null
              },
              {
                "color": "orange",
                "value": -80
              },
              {
                "color": "yellow",
                "value": -70
              },
              {
                "color": "dark-blue",
                "value": -60
              }
            ]
          },
          "unit": "dBm"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 24,
        "x": 0,
        "y": 28
      },
      "id": 3,
      "options": {
        "basemap": {
          "config": {
            "url": "http://openmower.2m.lt:5000/rgb/{z}/{x}/{y}.png?r=red&g=green&b=blue"
          },
          "name": "Layer 0",
          "type": "xyz"
        },
        "controls": {
          "mouseWheelZoom": true,
          "showAttribution": true,
          "showDebug": false,
          "showMeasure": false,
          "showScale": false,
          "showZoom": true
        },
        "layers": [
          {
            "config": {
              "showLegend": true,
              "style": {
                "color": {
                  "field": "homeassistant_sensor_signal_strength_dbm",
                  "fixed": "dark-green"
                },
                "opacity": 0.4,
                "rotation": {
                  "fixed": 0,
                  "max": 360,
                  "min": -360,
                  "mode": "mod"
                },
                "size": {
                  "fixed": 3,
                  "max": 15,
                  "min": 2
                },
                "symbol": {
                  "fixed": "img/icons/marker/circle.svg",
                  "mode": "fixed"
                },
                "textConfig": {
                  "fontSize": 12,
                  "offsetX": 0,
                  "offsetY": 0,
                  "textAlign": "center",
                  "textBaseline": "middle"
                }
              }
            },
            "location": {
              "mode": "auto"
            },
            "name": "WiFi Signal",
            "tooltip": false,
            "type": "markers"
          }
        ],
        "tooltip": {
          "mode": "details"
        },
        "view": {
          "allLayers": true,
          "id": "fit",
          "lat": 0,
          "lon": 0,
          "zoom": 22
        }
      },
      "pluginVersion": "10.0.3",
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "efa8b1d7-e94e-4886-a704-b61ce7c60a70"
          },
          "editorMode": "code",
          "expr": "homeassistant_sensor_unit_u0xb0{entity=~\".*openmower_position_(lat|lon)_high_freq\"}",
          "instant": false,
          "interval": "1s",
          "range": true,
          "refId": "A"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "efa8b1d7-e94e-4886-a704-b61ce7c60a70"
          },
          "editorMode": "code",
          "expr": "homeassistant_sensor_signal_strength_dbm{entity=\"sensor.openmower_rpi_wifi_signal_strength\"}",
          "hide": false,
          "instant": false,
          "interval": "1s",
          "range": true,
          "refId": "B"
        }
      ],
      "title": "WiFi Strength",
      "transformations": [
        {
          "id": "renameByRegex",
          "options": {
            "regex": ".*_lat_.*",
            "renamePattern": "lat"
          }
        },
        {
          "id": "renameByRegex",
          "options": {
            "regex": ".*_lon_.*",
            "renamePattern": "lon"
          }
        },
        {
          "id": "renameByRegex",
          "options": {
            "regex": ".*_wifi_.*",
            "renamePattern": "signal"
          }
        },
        {
          "id": "joinByField",
          "options": {}
        }
      ],
      "type": "geomap"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "1s",
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "OpenMower",
  "uid": "ec40a121-798b-44c9-b32e-2d396a6a4fa6",
  "version": 41,
  "weekStart": ""
}
