mqtt:
  sensor:
    - state_topic: "robot_state/json"
      name: "OpenMower Position Accuracy High Freq"
      unique_id: openmower_position_accuracy_high_freq
      device_class: distance
      icon: mdi:ruler
      value_template: "{{ value_json.pose.pos_accuracy | round(3) }}"
      unit_of_measurement: "m"

    - state_topic: "robot_state/json"
      name: "OpenMower Position Lat High Freq"
      unique_id: openmower_position_lat_high_freq
      icon: mdi:ruler
      value_template: >-
        {# https://stackoverflow.com/a/50506609 #}
        {% set earth = 6378.137 %}
        {% set pi = 3.14159265 %}
        {% set m = (1 / ((2 * pi / 360) * earth)) / 1000 %}
        {% set datum_lat = 55.952423 %}
        {% set datum_lon = 23.350276 %}
        {{ datum_lat + (value_json.pose.y * m) }}
      unit_of_measurement: "°"

    - state_topic: "robot_state/json"
      name: "OpenMower Position Lon High Freq"
      unique_id: openmower_position_lon_high_freq
      icon: mdi:ruler
      value_template: >-
        {# https://stackoverflow.com/a/50506609 #}
        {% set earth = 6378.137 %}
        {% set pi = 3.14159265 %}
        {% set m = (1 / ((2 * pi / 360) * earth)) / 1000 %}
        {% set datum_lat = 55.952423 %}
        {% set datum_lon = 23.350276 %}
        {{ datum_lon + (value_json.pose.x * m) / cos(datum_lat * (pi / 180)) }}
      unit_of_measurement: "°"
  
    - state_topic: "sensors/om_mow_esc_temp/data"
      name: "OpenMower Mower ESC Temperature High Freq"
      unique_id: openmower_mower_esc_temperature_high_freq
      device_class: temperature
      icon: mdi:thermometer
      value_template: "{{ value | round(2) }}"
      unit_of_measurement: "°C"
  
    - state_topic: "sensors/om_mow_motor_temp/data"
      name: "OpenMower Mower Motor Temperature High Freq"
      unique_id: openmower_mower_motor_temperature_high_freq
      device_class: temperature
      icon: mdi:thermometer
      value_template: "{{ value | round(2) }}"
      unit_of_measurement: "°C"
  
    - state_topic: "sensors/om_left_esc_temp/data"
      name: "OpenMower Left ESC Temperature High Freq"
      unique_id: openmower_left_esc_temperature_high_freq
      device_class: temperature
      icon: mdi:thermometer
      value_template: "{{ value | round(2) }}"
      unit_of_measurement: "°C"
  
    - state_topic: "sensors/om_right_esc_temp/data"
      name: "OpenMower Right ESC Temperature High Freq"
      unique_id: openmower_right_esc_temperature_high_freq
      device_class: temperature
      icon: mdi:thermometer
      value_template: "{{ value | round(2) }}"
      unit_of_measurement: "°C"
  
    - state_topic: "sensors/om_charge_current/data"
      name: "OpenMower Charge Current High Freq"
      unique_id: openmower_charge_current_hight_freq
      device_class: current
      icon: mdi:current-dc
      value_template: "{{ value | round(2) }}"
      unit_of_measurement: "A"
  
    - state_topic: "sensors/om_v_battery/data"
      name: "OpenMower Battery Voltage High Freq"
      unique_id: openmower_battery_voltage_high_freq
      device_class: voltage
      icon: mdi:sine-wave
      value_template: "{{ value | round(2) }}"
      unit_of_measurement: "V"

    - state_topic: "sensors/om_v_charge/data"
      name: "OpenMower Charge Voltage High Freq"
      unique_id: openmower_charge_voltage_high_freq
      device_class: voltage
      icon: mdi:sine-wave
      value_template: "{{ value | round(2) }}"
      unit_of_measurement: "V"
  
    - state_topic: "robot_state/json"
      name: "OpenMower Battery Percentage High Freq"
      unique_id: openmower_battery_percentage_high_freq
      device_class: battery
      icon: mdi:battery
      value_template: "{{ value_json.battery_percentage | round(2) | float * 100 }}"
      unit_of_measurement: "%"
  
    - state_topic: "robot_state/json"
      name: "OpenMower State"
      value_template: "{{ value_json.current_state }}"

  binary_sensor:
    - state_topic: "robot_state/json"
      name: "OpenMower Emergency"
      device_class: safety
      value_template: "{{ value_json.emergency }}"
      payload_on: "1"
      payload_off: "0"
  
    - state_topic: "robot_state/json"
      name: "OpenMower Charging"
      device_class: battery_charging
      value_template: "{{ value_json.is_charging }}"
      payload_on: "1"
      payload_off: "0"
      
sensor:
  - platform: filter
    name: "OpenMower Position Accuracy"
    entity_id: sensor.openmower_position_accuracy_high_freq
    filters:
      - filter: time_throttle
        window_size: "00:00:02"
      - filter: range
        upper_bound: 2
  - platform: filter
    name: "OpenMower Mower ESC Temperature"
    entity_id: sensor.openmower_mower_esc_temperature_high_freq
    filters:
      - filter: time_throttle
        window_size: "00:00:02"
  - platform: filter
    name: "OpenMower Mower Motor Temperature"
    entity_id: sensor.openmower_mower_motor_temperature_high_freq
    filters:
      - filter: time_throttle
        window_size: "00:00:02"
  - platform: filter
    name: "OpenMower Left ESC Temperature"
    entity_id: sensor.openmower_left_esc_temperature_high_freq
    filters:
      - filter: time_throttle
        window_size: "00:00:02"
  - platform: filter
    name: "OpenMower Right ESC Temperature"
    entity_id: sensor.openmower_right_esc_temperature_high_freq
    filters:
      - filter: time_throttle
        window_size: "00:00:02"
  - platform: filter
    name: "OpenMower Charge Current"
    entity_id: sensor.openmower_charge_current_high_freq
    filters:
      - filter: time_throttle
        window_size: "00:00:02"
  - platform: filter
    name: "OpenMower Battery Voltage"
    entity_id: sensor.openmower_battery_voltage_high_freq
    filters:
      - filter: time_throttle
        window_size: "00:00:02"
  - platform: filter
    name: "OpenMower Charge Voltage"
    entity_id: sensor.openmower_charge_voltage_high_freq
    filters:
      - filter: time_throttle
        window_size: "00:00:02"
  - platform: filter
    name: "OpenMower Battery Percentage"
    entity_id: sensor.openmower_battery_percentage_high_freq
    filters:
      - filter: time_throttle
        window_size: "00:00:02"
      
command_line:
  - sensor:
      name: "OpenMower RPi CPU Frequency"
      command: "ssh -i /config/.ssh/id_rsa openmower@openmower.local cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq"
      unit_of_measurement: "MHz"
      device_class: frequency
      value_template: "{{ value | multiply(0.001) | round(1) }}"
      scan_interval: 10
      
  - sensor:
      name: "OpenMower RPi CPU Temperature"
      command: "ssh -i /config/.ssh/id_rsa openmower@openmower.local cat /sys/class/thermal/thermal_zone0/temp"
      unit_of_measurement: "°C"
      value_template: "{{ value | multiply(0.001) | round(1) }}"
      scan_interval: 10
      
  - sensor:
      name: "OpenMower RPi WiFi Signal Strength"
      command: "ssh -i /config/.ssh/id_rsa openmower@openmower.local /usr/sbin/iwconfig wlan0 | grep Signal | cut -d= -f3 | cut -d' ' -f1"
      unit_of_measurement: "dBm"
      device_class: signal_strength
      scan_interval: 10